import { notFound } from "next/navigation";
import { MarketingShell } from "@/components/layout/MarketingShell";
import { FAQAccordion } from "@/components/marketing/FAQAccordion";
import { Hero } from "@/components/marketing/Hero";
import { HowItWorks } from "@/components/marketing/HowItWorks";
import { PricingCards } from "@/components/marketing/PricingCards";
import { ResultsGrid } from "@/components/marketing/ResultsGrid";
import {
  HOME_FAQ,
  HOME_PLANS,
  HOME_STEPS,
  MARKETPLACE_STATS,
  VERTICALS,
  isVertical,
} from "@/lib/marketing/site-content";

// Vertical slugs are real (naano.com/llms.txt "By vertical" section), but no
// per-vertical page design was available in the source scrape, so this page
// reuses the homepage's shared sections with a vertical-specific heading.
const VERTICAL_LABELS: Record<string, string> = {
  "sales-tech": "Sales-tech",
  revops: "RevOps",
  devtools: "Devtools",
  product: "Product & PM tools",
  "hr-tech": "HR-tech",
  fintech: "Fintech",
  "marketing-ops": "Martech & marketing-ops",
  "vertical-saas": "Vertical SaaS",
};

export function generateStaticParams() {
  return VERTICALS.map((vertical) => ({ vertical }));
}

export default async function VerticalPage({ params }: PageProps<"/for/[vertical]">) {
  const { vertical } = await params;

  if (!isVertical(vertical)) {
    notFound();
  }

  const label = VERTICAL_LABELS[vertical] ?? vertical;

  return (
    <MarketingShell>
      <Hero
        eyebrow={`For ${label} teams`}
        heading="The B2B LinkedIn"
        highlight="Creator Marketplace."
        description={`Find the creators your ${label} buyers already trust, launch campaigns in days, and track the clicks, leads and pipeline generated by every post.`}
        primaryCta={{ label: "Launch a campaign", href: "/register" }}
        secondaryCta={{ label: "See how Naano works", href: `/for/${vertical}#how-it-works` }}
      />
      <ResultsGrid heading="Work with all the best creators." stats={MARKETPLACE_STATS} />
      <HowItWorks heading="Run creator campaigns from one place." steps={HOME_STEPS} />
      <PricingCards heading="Start free. Upgrade when you want your time back." plans={HOME_PLANS} variant="summary" />
      <FAQAccordion heading="Frequently asked questions" items={HOME_FAQ} />
    </MarketingShell>
  );
}
